name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install bandit safety

    - name: Run Bandit SAST
      run: bandit -r . -lll --exit-zero

    - name: Run Safety check
      run: safety check -r requirements.txt || true

    - name: Build Docker image
      run: docker build -t vulnapp:latest .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: vulnapp:latest
        format: table
        exit-code: 0
        ignore-unfixed: true

    - name: Run Docker container
      run: docker run -d -p 5000:5000 vulnapp:latest
